name: Action Lint

on: 
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rethab/actions-lint@v1
        with:
          files: .github/workflows/dockerBuild.yml